### ISSUE TITLE
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.android.server.scannerservice.broadcast flg=0x10 (has extras) } in com.shinow.pda_scanner.PdaScannerPlugin$1@3aeda31f Process: com.example.ys_pda, PID: 21418

### ISSUE THREAD

**Issue by Joseph0717** [leyan95/pda_scanner#12]
Flutter：2.2.2  
Dart 2.13.3
pda_scanner: ^0.2.9

## Steps to Reproduce
[![RHwCdJ.png](https://z3.ax1x.com/2021/07/07/RHwCdJ.png)](https://imgtu.com/i/RHwCdJ)

## Logs
Launching lib\main.dart on PDT 90P in debug mode...
lib\main.dart:1
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:51123/JgsC93lg0fE=/ws
D/AndroidRuntime(21619): Shutting down VM
E/AndroidRuntime(21619): FATAL EXCEPTION: main
E/AndroidRuntime(21619): Process: com.example.ys_pda, PID: 21619
E/AndroidRuntime(21619): java.lang.RuntimeException: Error receiving broadcast Intent { act=com.android.server.scannerservice.broadcast flg=0x10 (has extras) } in com.shinow.pda_scanner.PdaScannerPlugin$1@3aeda31f
E/AndroidRuntime(21619): 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:876)
E/AndroidRuntime(21619): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(21619): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(21619): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(21619): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(21619): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21619): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(21619): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
E/AndroidRuntime(21619): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
E/AndroidRuntime(21619): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.EventChannel$EventSink.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(21619): 	at com.shinow.pda_scanner.PdaScannerPlugin$1.onReceive(PdaScannerPlugin.java:30)
E/AndroidRuntime(21619): 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:866)
E/AndroidRuntime(21619): 	... 8 more
I/Process (21619): Sending signal. PID: 21619 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by Joseph0717** [comment]
进入页面 - 扫描 - 报错 - 退出

**Comment by Joseph0717** [comment]
已解决，原因:跟组件未混入

**Comment by renpengfeier** [comment]
> 已解决，原因:跟组件未混入

你的flutter版本2.2.2，是怎么支持null safety的？

**Comment by Joseph0717** [comment]
> > 已解决，原因:跟组件未混入
> 
> 你的flutter版本2.2.2，是怎么支持null safety的？

我的项目没有支持null safety，新手，不太懂
```
environment:
  sdk: ">=2.7.0 <3.0.0"
```
